# Generated by Django 2.0.13 on 2020-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=1000)),
                ('author_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('date_time', models.DateField()),
                ('date_write', models.DateField()),
                ('picture', models.ImageField(upload_to='new_picture')),
            ],
        ),
    ]
