# Generated by Django 2.0.13 on 2020-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacsi',
            name='bacsi_gioitinh',
            field=models.BooleanField(default=0),
        ),
    ]
